project:
  type: website
  output-dir: docs


website:
  title: "Chloe Kerstein"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: education.qmd
        text: Education

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



